### ISSUE TITLE
v1.3.8 does not have an -a or -d parameter

### ISSUE THREAD

**Issue by KenVanGilbergen** [ozymandias547/snaptest-cli#2]
It seems the snaptest exporter commandline was updated in the chrome extension, but where do we get the latest source for the cli tool ?

**Comment by ozymandias547** [comment]
We are fixing this right away.  Stay tuned.

**Comment by ozymandias547** [comment]
@KenVanGilbergen Updated cli has been published.  Please update to v2.0.0 (snaptest-cli@2.0.0)

**Comment by KenVanGilbergen** [comment]
Thank you for the quick fix, seems to work fine.
